# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1213120510);
user_pref("app.update.lastUpdateTime.background-update-timer", 1213120502);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1213120510);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1213120513);
user_pref("browser.bookmarks.livemark_refresh_seconds", 31536000);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.download.manager.retention", 0);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.formfill.enable", false);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.safebrowsing.enabled", false);
user_pref("browser.search.suggest.enabled", false);
user_pref("browser.search.update", false);
user_pref("browser.send_pings", false);
user_pref("browser.sessionstore.enabled", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage_override.mstone", "rv:1.8.1.14");
user_pref("dom.storage.enabled", false);
user_pref("extensions.lastAppVersion", "2.0.0.14");
user_pref("extensions.torbutton.custom.socks_host", "localhost");
user_pref("extensions.torbutton.custom.socks_port", 9050);
user_pref("extensions.torbutton.locked_mode", true);
user_pref("extensions.torbutton.saved.http_port", 8118);
user_pref("extensions.torbutton.saved.http_proxy", "127.0.0.1");
user_pref("extensions.torbutton.saved.https_port", 8118);
user_pref("extensions.torbutton.saved.https_proxy", "127.0.0.1");
user_pref("extensions.torbutton.saved.share_proxy_settings", false);
user_pref("extensions.torbutton.saved.socks_host", "localhost");
user_pref("extensions.torbutton.saved.socks_port", 9050);
user_pref("extensions.torbutton.saved.socks_remote_dns", true);
user_pref("extensions.torbutton.saved.socks_version", 5);
user_pref("extensions.torbutton.saved.type", 1);
user_pref("extensions.torbutton.socks_host", "127.0.0.1");
user_pref("extensions.torbutton.socks_port", 9050);
user_pref("extensions.torbutton.tor_enabled", true);
user_pref("extensions.torbutton.use_privoxy", false);
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("general.appname.override", "Netscape");
user_pref("general.appversion.override", "5.0 (Windows; en-US)");
user_pref("general.buildID.override", "0");
user_pref("general.oscpu.override", "Windows NT 5.1");
user_pref("general.platform.override", "Win32");
user_pref("general.productSub.override", "20080404");
user_pref("general.useragent.override", "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.14) Gecko/20080404 Firefox/2.0.0.14");
user_pref("general.useragent.vendor", "");
user_pref("general.useragent.vendorSub", "");
user_pref("intl.accept_languages", "en-us, en");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("layout.css.report_errors", false);
user_pref("network.cookie.lifetimePolicy", 2);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.dns.disableIPv6", true);
user_pref("network.protocol-handler.warn-external.mailto", true);
user_pref("network.protocol-handler.warn-external.news", true);
user_pref("network.protocol-handler.warn-external.nntp", true);
user_pref("network.protocol-handler.warn-external.snews", true);
user_pref("network.proxy.socks", "127.0.0.1");
user_pref("network.proxy.socks_port", 9050);
user_pref("network.proxy.socks_remote_dns", true);
user_pref("network.proxy.type", 1);
user_pref("network.security.ports.banned", "8118,8123,9050,9051");
user_pref("plugin.disable_full_page_plugin_for_types", "application/asx,video/x-ms-asf-plugin,application/x-mplayer2,video/x-ms-asf,video/x-ms-wm,audio/x-ms-wma,audio/x-ms-wax,video/x-ms-wmv,video/x-ms-wvx,application/x-drm-v2,application/x-drm");
user_pref("security.enable_java", false);
user_pref("security.xpconnect.plugin.unrestricted", false);
user_pref("signon.rememberSignons", false);
user_pref("urlclassifier.tableversion.goog-black-enchash", "1.52683");
user_pref("urlclassifier.tableversion.goog-black-url", "1.22057");
user_pref("urlclassifier.tableversion.goog-white-domain", "1.480");
user_pref("urlclassifier.tableversion.goog-white-url", "1.371");
