# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.auto", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1218224737);
user_pref("app.update.lastUpdateTime.background-update-timer", 1218224737);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1218224737);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1218291339);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.send_pings", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage", "https://check.torproject.org/?lang=de");
user_pref("browser.startup.homepage_override.mstone", "rv:1.8.1.16");
user_pref("extensions.lastAppVersion", "2.0.0.16");
user_pref("extensions.torbutton.fresh_install", false);
user_pref("extensions.torbutton.http_port", 8118);
user_pref("extensions.torbutton.http_proxy", "127.0.0.1");
user_pref("extensions.torbutton.https_port", 8118);
user_pref("extensions.torbutton.https_proxy", "127.0.0.1");
user_pref("extensions.torbutton.locked_mode", true);
user_pref("extensions.torbutton.saved.auto_update", false);
user_pref("extensions.torbutton.saved.share_proxy_settings", false);
user_pref("extensions.torbutton.saved.socks_version", 5);
user_pref("extensions.torbutton.socks_host", "127.0.0.1");
user_pref("extensions.torbutton.socks_port", 9050);
user_pref("extensions.torbutton.tor_memory_jar", true);
user_pref("extensions.update.notifyUser", false);
user_pref("general.useragent.locale", "BUNDLELOCALE");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.security.ports.banned", "8118,8123,9050,9051");
user_pref("security.warn_entering_secure", false);
user_pref("security.warn_entering_secure.show_once", false);
user_pref("security.warn_leaving_secure", false);
user_pref("security.warn_leaving_secure.show_once", false);
user_pref("urlclassifier.tableversion.goog-black-enchash", "1.55536");
user_pref("urlclassifier.tableversion.goog-black-url", "1.23256");
user_pref("urlclassifier.tableversion.goog-white-domain", "1.481");
user_pref("urlclassifier.tableversion.goog-white-url", "1.371");
