# Mozilla User Preferences

/* Do not edit this file.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("browser.sessionstore.enabled", false);
user_pref("dom.storage.enabled", false);
user_pref("extensions.torbutton.custom.socks_host", "localhost");
user_pref("extensions.torbutton.custom.socks_port", 9050);
user_pref("extensions.torbutton.saved.share_proxy_settings", false);
user_pref("extensions.torbutton.saved.socks_host", "localhost");
user_pref("extensions.torbutton.saved.socks_port", 9050);
user_pref("extensions.torbutton.saved.socks_remote_dns", true);
user_pref("extensions.torbutton.saved.socks_version", 5);
user_pref("extensions.torbutton.saved.type", 1);
user_pref("extensions.torbutton.socks_host", "localhost");
user_pref("extensions.torbutton.socks_port", 9050);
user_pref("extensions.torbutton.tor_enabled", true);
user_pref("extensions.torbutton.use_privoxy", false);
user_pref("layout.css.report_errors", false);
user_pref("network.dns.disableIPv6", true);
user_pref("security.xpconnect.plugin.unrestricted", false);
